package main

// setupTemplate contains the player setup page
const setupTemplate = `
<!DOCTYPE html>
<html>
<head>
    <title>Flag Quiz Game - Player Setup</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f0f8ff;
        }
        .container {
            background-color: white;
            padding: 5px;
            border-radius: 5px;
            box-shadow: 0 4px 5px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            text-align: center;
            margin-bottom: 30px;
        }
        .setup-section {
            margin: 30px 0;
        }
        label {
            display: block;
            font-size: 16px;
            color: #2c3e50;
            margin-bottom: 10px;
            font-weight: bold;
        }
        input[type="number"], input[type="text"] {
            width: 100%;
            padding: 12px;
            font-size: 16px;
            border: 2px solid #bdc3c7;
            border-radius: 8px;
            box-sizing: border-box;
            margin-bottom: 15px;
        }
        input[type="number"]:focus, input[type="text"]:focus {
            outline: none;
            border-color: #3498db;
        }
        .player-inputs {
            margin-top: 20px;
        }
        .player-input {
            margin-bottom: 15px;
        }
        .btn {
            width: 100%;
            font-size: 18px;
            padding: 15px;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-weight: bold;
            transition: all 0.3s ease;
            background-color: #27ae60;
            color: white;
        }
        .btn:hover {
            background-color: #229954;
        }
        .btn:disabled {
            background-color: #95a5a6;
            cursor: not-allowed;
        }
        .info {
            text-align: center;
            color: #7f8c8d;
            font-size: 14px;
            margin-top: 20px;
        }
    </style>
    <script>
        function updatePlayerInputs() {
            const numPlayers = parseInt(document.getElementById('numPlayers').value) || 1;
            const container = document.getElementById('playerInputs');
            const limitedPlayers = Math.min(Math.max(numPlayers, 1), 4);
            
            if (numPlayers !== limitedPlayers) {
                document.getElementById('numPlayers').value = limitedPlayers;
            }
            
            container.innerHTML = '';
            for (let i = 0; i < limitedPlayers; i++) {
                const div = document.createElement('div');
                div.className = 'player-input';
                div.innerHTML = '<label for="player' + (i+1) + '">Player ' + (i+1) + ' Name:</label>' +
                               '<input type="text" id="player' + (i+1) + '" name="playerName" placeholder="Enter name" required>';
                container.appendChild(div);
            }
        }
        
        window.onload = function() {
            updatePlayerInputs();
        };
    </script>
</head>
<body>
    <div class="container">
        <h1>🏴 Flag Quiz Game</h1>
        <h2 style="text-align: center; color: #7f8c8d; margin-top: -20px;">Player Setup</h2>
        
        <form method="POST" action="/setup">
            <div class="setup-section">
                <label for="numPlayers">Number of Players (1-4):</label>
                <input type="number" id="numPlayers" min="1" max="4" value="1" onchange="updatePlayerInputs()" required>
            </div>
            
            <div class="setup-section">
                <label for="numRounds">Number of Rounds:</label>
                <input type="number" id="numRounds" name="numRounds" min="1" max="50" value="10" required>
            </div>
            
            <div class="player-inputs" id="playerInputs">
                <!-- Player inputs will be generated by JavaScript -->
            </div>
            
            <button type="submit" class="btn">Start Game</button>
            
            <div class="info">Enter names for each player and click Start Game to begin!</div>
        </form>
    </div>
</body>
</html>
`

// htmlTemplate contains the HTML template for the flag quiz game
const htmlTemplate = `
<!DOCTYPE html>
<html>
<head>
    <title>Flag Quiz Game</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 900px;
            margin: 20px auto;
            padding: 20px;
            background-color: #f0f8ff;
        }
        .container {
            background-color: white;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            text-align: center;
            margin-bottom: 10px;
        }
        .subtitle {
            text-align: center;
            color: #7f8c8d;
            margin-bottom: 30px;
            font-style: italic;
        }
        .game-area {
            text-align: center;
            margin: 30px 0;
        }
        .flag-container {
            display: inline-block;
            border: 3px solid #34495e;
            border-radius: 10px;
            overflow: hidden;
            margin: 20px 0;
            box-shadow: 0 2px 10px rgba(0,0,0,0.2);
        }
        .flag-image {
            display: block;
            max-height: 100%;
            max-width: 200%;
        }
        .question {
            font-size: 24px;
            color: #2c3e50;
            margin: 20px 0;
            font-weight: bold;
        }
        .country-name {
            font-size: 20px;
            color: #e74c3c;
            margin: 15px 0;
            font-weight: bold;
        }
        .current-turn {
            font-size: 18px;
            color: #3498db;
            margin: 10px 0;
            font-weight: bold;
            font-style: italic;
        }
        .buttons {
            margin: 30px 0;
        }
        .btn {
            font-size: 18px;
            padding: 15px 30px;
            margin: 10px;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-weight: bold;
            transition: all 0.3s ease;
        }
        .btn-correct {
            background-color: #27ae60;
            color: white;
        }
        .btn-correct:hover {
            background-color: #229954;
        }
        .btn-incorrect {
            background-color: #e74c3c;
            color: white;
        }
        .btn-incorrect:hover {
            background-color: #c0392b;
        }
        .btn-new {
            background-color: #3498db;
            color: white;
        }
        .btn-new:hover {
            background-color: #2980b9;
        }
        .result {
            font-size: 20px;
            font-weight: bold;
            margin: 20px 0;
            padding: 15px;
            border-radius: 8px;
        }
        .result.correct {
            background-color: #d5f4e6;
            color: #27ae60;
            border: 2px solid #27ae60;
        }
        .result.incorrect {
            background-color: #fadbd8;
            color: #e74c3c;
            border: 2px solid #e74c3c;
        }
        .score {
            background-color: #ebf3fd;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .score h3 {
            margin: 0 0 15px 0;
            color: #2c3e50;
            text-align: center;
        }
        .player-score {
            background-color: white;
            border: 2px solid #d1d8e0;
            border-radius: 8px;
            padding: 12px;
            margin-bottom: 10px;
            transition: all 0.3s ease;
        }
        .player-score.current-player {
            border-color: #3498db;
            background-color: #e8f4f8;
            box-shadow: 0 2px 8px rgba(52, 152, 219, 0.3);
        }
        .player-name {
            font-size: 18px;
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 10px;
            text-align: center;
        }
        .current-player .player-name {
            color: #3498db;
        }
        .stats {
            display: flex;
            justify-content: space-around;
            flex-wrap: wrap;
        }
        .stat {
            margin: 5px;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #3498db;
        }
        .stat-label {
            font-size: 14px;
            color: #7f8c8d;
        }
        .flag-comparison {
            display: flex;
            justify-content: center;
            gap: 20px;
            margin: 20px 0;
            flex-wrap: wrap;
        }
        .flag-box {
            text-align: center;
            padding: 10px;
            border-radius: 8px;
            background-color: #f8f9fa;
            border: 2px solid #dee2e6;
            min-width: 120px;
        }
        .flag-box h4 {
            margin: 0 0 10px 0;
            font-size: 14px;
            color: #495057;
        }
        .flag-thumbnail {
            display: block;
            max-width: 100%;
            height: auto;
            border: 2px solid #333;
            border-radius: 4px;
            object-fit: cover;
        }
        .final-results {
            background-color: #fff;
            border: 3px solid #f39c12;
            border-radius: 10px;
            padding: 20px;
            margin: 20px 0;
        }
        .final-results h2 {
            color: #2c3e50;
            margin-top: 0;
            text-align: center;
        }
        .final-player {
            font-size: 18px;
            padding: 12px;
            margin: 10px 0;
            background-color: #ecf0f1;
            border-radius: 5px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🏴 Flag Quiz Game</h1>
        <div class="subtitle">Can you spot the fake flags?</div>
        
        <div class="score">
            <h3>Scoreboard {{if .TotalRounds}}(Round {{.CurrentRound}}/{{.TotalRounds}}){{end}}</h3>
            {{range $index, $player := .Players}}
            <div class="player-score {{if eq $index $.CurrentPlayer}}current-player{{end}}">
                <div class="player-name">
                    {{if eq $index $.CurrentPlayer}}▶{{end}} {{$player.Name}}
                </div>
                <div class="stats">
                    <div class="stat">
                        <div class="stat-value">{{$player.Correct}}</div>
                        <div class="stat-label">Correct</div>
                    </div>
                    <div class="stat">
                        <div class="stat-value">{{$player.Incorrect}}</div>
                        <div class="stat-label">Incorrect</div>
                    </div>
                    <div class="stat">
                        <div class="stat-value">{{$player.Total}}</div>
                        <div class="stat-label">Total</div>
                    </div>
                    <div class="stat">
                        <div class="stat-value">{{$player.Percentage}}%</div>
                        <div class="stat-label">Accuracy</div>
                    </div>
                </div>
            </div>
            {{end}}
        </div>

        <div class="game-area">
            {{if .GameOver}}
                <div class="question">🏆 Game Over! 🏆</div>
                <div class="final-results">
                    <h2>Final Results</h2>
                    {{range .Players}}
                    <div class="final-player">
                        <strong>{{.Name}}</strong>: {{.Correct}} correct out of {{.Total}} ({{.Percentage}}%)
                    </div>
                    {{end}}
                </div>
                <button class="btn btn-new" onclick="location.href='/setup'">New Game</button>
            {{else if .FlagData}}
                <div class="question">Is this the correct flag?</div>
                <div class="country-name">{{.CountryName}}</div>
                {{if .Players}}
                <div class="current-turn">{{(index .Players .CurrentPlayer).Name}}'s turn</div>
                {{end}}
                <div class="flag-container">
                    <img src="data:image/png;base64,{{.FlagData}}" alt="Flag" class="flag-image">
                </div>
                
                {{if .ShowResult}}
                    <div class="result {{if .ResultCorrect}}correct{{else}}incorrect{{end}}">
                        {{if .ResultCorrect}}
                            ✓ Correct! {{.ResultMessage}}
                        {{else}}
                            ✗ Wrong! {{.ResultMessage}}
                            {{if and .OriginalFlag .ModifiedFlag (not .IsCorrect)}}
                                <div class="flag-comparison">
                                    <div class="flag-box">
                                        <h4>Correct Flag</h4>
                                        <img src="data:image/png;base64,{{.OriginalFlag}}" alt="Correct Flag" class="flag-thumbnail">
                                    </div>
                                </div>
                            {{end}}
                        {{end}}
                    </div>
                    <button class="btn btn-new" onclick="location.href='/new'">Next Flag</button>
                {{else}}
                    <div class="buttons">
                        <button class="btn btn-correct" onclick="location.href='/guess?answer=correct'">Correct Flag</button>
                        <button class="btn btn-incorrect" onclick="location.href='/guess?answer=incorrect'">Fake Flag</button>
                    </div>
                {{end}}
            {{else}}
                <div class="question">Welcome to the Flag Quiz!</div>
                <p>Test your knowledge of world flags. Some flags will be correct, others will have subtle errors.</p>
                <button class="btn btn-new" onclick="location.href='/new'">Start Game</button>
            {{end}}
        </div>
    </div>
</body>
</html>
`
